# Generated by Django 5.0 on 2024-07-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_time_balance_booking_space_user_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_users', to='core.space'),
        ),
    ]
